from __future__ import annotations

from typing import Any


def example(payload: dict[str, Any]) -> dict[int | str, dict[str, Any]]:
    """A sample 200 body for the docs, shaped the way the endpoint answers."""
    return {200: {"content": {"application/json": {"example": payload}}}}


# Captured from live responses, with handles, titles, URLs and bodies replaced.

HEALTH = {'status': 'ok',
 'mongo': True,
 'last_crawl': '2026-08-18T09:12:44Z',
 'stale': False,
 'sitemap': {'last_checked': '2026-08-06T00:15:36.356000Z',
             'last_synced': '2026-08-06T00:15:36.356000Z',
             'counts': {'seen': 30388,
                        'new': 26,
                        'promoted': 26,
                        'skipped': 3,
                        'delisted': 1}},
 'now': '2026-08-18T09:14:02Z'}

META = {'counts': {'projects': 388,
            'devlogs': 2969,
            'ships': 478,
            'comments': 36,
            'users': 1,
            'shop_items': 0,
            'shop_snapshots': 0,
            'project_snapshots': 11066,
            'devlog_snapshots': 358,
            'user_snapshots': 3,
            'global_snapshots': 0},
 'metrics': {'project': ['comments',
                         'devlogs',
                         'followers',
                         'latest_multiplier',
                         'likes',
                         'paid_hours',
                         'reposts',
                         'shipped_hours',
                         'ships',
                         'stardust_total',
                         'total_hours',
                         'views'],
             'devlog': ['comments', 'duration_seconds', 'likes', 'reposts', 'views'],
             'user': ['achievements_earned',
                      'avg_multiplier',
                      'best_multiplier',
                      'comment_chars',
                      'comment_threads',
                      'comments_received',
                      'comments_sent',
                      'comments_to_others',
                      'devlogs',
                      'followers',
                      'following',
                      'hours',
                      'likes_received',
                      'mission_stardust',
                      'paid_hours',
                      'projects',
                      'projects_commented',
                      'reposts_received',
                      'ship_stardust',
                      'shipped_hours',
                      'ships',
                      'streak',
                      'views_received',
                      'voted_stardust',
                      'votes'],
             'shop': ['price_au',
                      'price_ca',
                      'price_eu',
                      'price_in',
                      'price_uk',
                      'price_us',
                      'price_xx',
                      'purchases',
                      'regions_available',
                      'remaining_stock',
                      'sale_percentage'],
             'global': ['comments',
                        'comments_seen',
                        'devlogs',
                        'followers',
                        'hours',
                        'likes',
                        'paid_hours',
                        'projects',
                        'projects_known',
                        'reposts',
                        'shipped_hours',
                        'ships',
                        'shop_items',
                        'shop_items_on_sale',
                        'stardust_paid',
                        'threads_pending',
                        'users',
                        'users_known',
                        'views']},
 'history': {'intervals': ['1h', '1d', '1w'],
             'fill': ['none', 'locf'],
             'max_buckets': 20000,
             'note': 'A point is written when a tracked number moves, plus a daily '
                     'heartbeat. Deltas are computed per request, never stored.'},
 'coverage': {'users_complete': 1,
              'users_partial': 0,
              'projects_listed': 3525,
              'projects_tracked': 3526,
              'projects_crawled': 388,
              'users_listed': 26851,
              'users_tracked': 26852,
              'users_crawled': 1,
              'threads_read': 21,
              'threads_pending': 35},
 'data_source': 'public pages of stardance.hackclub.com',
 'caveats': ['Rejected ships, deleted devlogs and unverified profiles are not publicly '
             'visible.',
             'Points marked synthetic are reconstructed from timestamps, not observed.',
             "Rankings are computed from rows we crawled, not from Stardance's own "
             'leaderboard, which is opt-in and ranks on stale approx_ columns.',
             'ship_stardust counts ship payouts only, and is a lower bound until every '
             "one of a user's projects has been crawled. See coverage.complete.",
             'Devlog history starts when we first crawled the card, not when the '
             'devlog was posted, so its early engagement is not recoverable.',
             "Comments are read one thread at a time, queued when a devlog's counter "
             'moves, so comments_sent trails comments_received until the queue drains. '
             'Threads never render deleted comments or banned authors, and those stay '
             'in the counter, so a thread can hold fewer comments than it counts.',
             'Global history sums the rows we hold, so early growth is partly our own '
             "crawl catching up rather than the platform's.",
             'Shop prices are per region and are read as a signed-out visitor. That is '
             'the list price everyone pays, except on Outpost tickets, where a '
             'per-user discount we cannot see is subtracted at checkout.']}

PROJECT_LIST = {'metric': 'stardust_total',
 'source': 'computed from crawled project pages',
 'total': 388,
 'limit': 1,
 'offset': 0,
 'items': [{'rank': 1,
            'project_id': 8100,
            'title': 'Nixie Tube Desk Clock',
            'description': 'Six IN-14 tubes, a custom boost converter and far too much '
                           'brass.',
            'banner_url': 'https://stardance.example/uploads/banner.png',
            'demo_url': 'https://example.com/project',
            'repo_url': 'https://example.com/project',
            'owner_id': 11155,
            'owner_username': 'quartzfox',
            'owner_avatar_url': 'https://stardance.example/avatars/1177.png',
            'members': ['quartzfox'],
            'is_super_star': True,
            'is_hardware': False,
            'mission': None,
            'value': 3042,
            'stats': {'devlogs': 111,
                      'total_hours': 266.0,
                      'summed_hours': 266.23,
                      'shipped_hours': 167.0,
                      'paid_hours': 167.0,
                      'followers': 74,
                      'likes': 286,
                      'comments': 39,
                      'reposts': 9,
                      'views': 8597,
                      'ships': 2,
                      'stardust_total': 3042,
                      'voted_stardust': 3042,
                      'mission_stardust': 0,
                      'latest_multiplier': 19.65,
                      'avg_multiplier': 19.715,
                      'stardust_per_paid_hour': 18.22,
                      'unpaid_hours': 99.23,
                      'ratable_unpaid_hours': 99.23,
                      'mission_pending_hours': 0.0,
                      'mission_pending_stardust': 0,
                      'estimated_pending_stardust': 1808,
                      'estimated_total_stardust': 4850,
                      'fixed_payout_hours': 0.0,
                      'flat_rate_hours': 0.0},
            'created_at_estimate': '2026-06-05T18:56:50Z',
            'first_seen': '2026-08-04T18:03:06.470000Z',
            'last_changed': '2026-08-13T21:24:41.810000Z'}],
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

PROJECT_SEARCH = {'query': 'a',
 'metric': 'stardust_total',
 'total': 1,
 'items': [{'rank': 167,
            'project_id': 10054,
            'title': 'Handheld Spectrometer',
            'description': 'Six IN-14 tubes, a custom boost converter and far too much '
                           'brass.',
            'banner_url': 'https://stardance.example/uploads/banner.png',
            'demo_url': 'https://example.com/project',
            'repo_url': 'https://example.com/project',
            'owner_id': None,
            'owner_username': 'solderqueen',
            'owner_avatar_url': 'https://stardance.example/avatars/1177.png',
            'members': ['solderqueen'],
            'is_super_star': False,
            'is_hardware': False,
            'mission': None,
            'value': 0,
            'stats': {'devlogs': 6,
                      'total_hours': 10.0,
                      'summed_hours': 9.8,
                      'shipped_hours': 10.0,
                      'paid_hours': None,
                      'followers': 0,
                      'likes': 7,
                      'comments': 0,
                      'reposts': 0,
                      'views': 62,
                      'ships': 1,
                      'stardust_total': 0,
                      'latest_multiplier': None,
                      'avg_multiplier': None,
                      'stardust_per_paid_hour': None,
                      'unpaid_hours': 9.8,
                      'estimated_pending_stardust': None,
                      'estimated_total_stardust': None},
            'created_at_estimate': '2026-06-13T12:48:50Z',
            'first_seen': '2026-08-05T22:38:34.289000Z',
            'last_changed': '2026-08-05T22:38:34.289000Z',
            'exact': False}],
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

PROJECT_METRICS = {'metrics': ['avg_multiplier',
             'comments',
             'devlogs',
             'estimated_total_stardust',
             'followers',
             'latest_multiplier',
             'likes',
             'paid_hours',
             'reposts',
             'shipped_hours',
             'ships',
             'stardust_per_paid_hour',
             'stardust_total',
             'total_hours',
             'unpaid_hours',
             'views'],
 'chartable': ['comments',
               'devlogs',
               'followers',
               'latest_multiplier',
               'likes',
               'paid_hours',
               'reposts',
               'shipped_hours',
               'ships',
               'stardust_total',
               'total_hours',
               'views'],
 'note': 'stardust_total counts rated ship payouts plus what a mission pays directly. '
         'Nothing a project earned off its own page is visible to us.'}

PROJECT = {'_id': 8100,
 'banner_url': 'https://stardance.example/uploads/banner.png',
 'created_at_estimate': '2026-06-05T18:56:50Z',
 'demo_url': 'https://example.com/project',
 'description': 'Six IN-14 tubes, a custom boost converter and far too much brass.',
 'first_seen': '2026-08-04T18:03:06.470000Z',
 'is_hardware': False,
 'is_super_star': True,
 'last_changed': '2026-08-13T21:24:41.810000Z',
 'last_crawled': '2026-08-18T09:12:44Z',
 'members': ['quartzfox'],
 'owner_avatar_url': 'https://stardance.example/avatars/1177.png',
 'owner_username': 'quartzfox',
 'repo_url': 'https://example.com/project',
 'stats': {'devlogs': 111,
           'total_hours': 266.0,
           'summed_hours': 266.23,
           'shipped_hours': 167.0,
           'paid_hours': 167.0,
           'followers': 74,
           'likes': 286,
           'comments': 39,
           'reposts': 9,
           'views': 8597,
           'ships': 2,
           'stardust_total': 3042,
           'voted_stardust': 3042,
           'mission_stardust': 0,
           'latest_multiplier': 19.65,
           'avg_multiplier': 19.715,
           'stardust_per_paid_hour': 18.22,
           'unpaid_hours': 99.23,
           'ratable_unpaid_hours': 99.23,
           'mission_pending_hours': 0.0,
           'mission_pending_stardust': 0,
           'estimated_pending_stardust': 1808,
           'estimated_total_stardust': 4850,
           'fixed_payout_hours': 0.0,
           'flat_rate_hours': 0.0},
 'super_star_at': '2026-06-16T12:22:56Z',
 'super_star_by': 'cskartikey',
 'super_star_note': 'As a prize for your great work, look out for a bonus prize in the '
                    'mail :)',
 'title': 'Nixie Tube Desk Clock',
 'member_ids': [11155],
 'owner_id': 11155,
 'mission': None,
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

PROJECT_DEVLOGS = {'project_id': 8100,
 'total': 111,
 'limit': 1,
 'offset': 0,
 'items': [{'_id': 38397,
            'avatar_url': 'https://stardance.example/avatars/1177.png',
            'body_preview': 'Boost converter finally holds 170 V without screaming. '
                            'Photos below.',
            'comments': 1,
            'comments_stale': False,
            'duration_seconds': 4109,
            'image_urls': ['https://stardance.example/uploads/banner.png'],
            'last_crawled': '2026-08-18T09:12:44Z',
            'likes': 5,
            'post_id': 45634,
            'posted_at': '2026-08-12T08:01:02Z',
            'project_id': 8100,
            'reposts': 0,
            'snapshot_at': '2026-08-18T09:12:44Z',
            'username': 'quartzfox',
            'username_lower': 'quartzfox',
            'views': 76,
            'user_id': 11155,
            'media': [{'kind': 'image', 'url': 'https://example.com/project'}],
            'body': 'Boost converter finally holds 170 V without screaming. Photos '
                    'below.',
            'comments_crawled_at': '2026-08-13T22:49:21.063000Z',
            'comments_crawled_count': 1,
            'comments_seen': 1}],
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

PROJECT_COMMENTS = {'project_id': 8100,
 'comments_count': 39,
 'total': 36,
 'limit': 1,
 'offset': 0,
 'commenters': 17,
 'top_commenters': [{'comments': 12, 'username': 'quartzfox', 'threads': 11}],
 'items': [{'_id': 8460,
            'body': 'Boost converter finally holds 170 V without screaming. Photos '
                    'below.',
            'body_length': 68,
            'devlog_id': 38397,
            'first_seen': '2026-08-13T22:49:21.063000Z',
            'images': [],
            'is_self': False,
            'last_crawled': '2026-08-18T09:12:44Z',
            'mentions': [],
            'position': 0,
            'posted_at': '2026-08-13T04:44:20Z',
            'project_id': 8100,
            'username': 'brasswren',
            'username_lower': 'brasswren'}],
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

PROJECT_SHIPS = {'project_id': 8100,
 'total': 2,
 'stardust_total': 3042,
 'items': [{'_id': 16508,
            'post_id': 16508,
            'project_id': 8100,
            'ship_number': 1,
            'username': 'quartzfox',
            'shipped_at': '2026-06-26T21:15:26Z',
            'devlogs_at_ship': 46,
            'hours_at_ship': 134.0,
            'multiplier': 19.78,
            'payout': 2409,
            'status': 'approved',
            'payout_blessing': None,
            'mission': None,
            'mission_slug': None,
            'body': 'Boost converter finally holds 170 V without screaming. Photos '
                    'below.',
            'payout_hours': 121.79,
            'payout_path': 'voting',
            'mission_stardust': None,
            'mission_pending_stardust': None,
            'username_lower': 'quartzfox',
            'last_crawled': '2026-08-18T09:12:44Z',
            'user_id': 11155}],
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

HISTORY = {'interval': '1d',
 'fill': 'none',
 'buckets': 63,
 'observed_buckets': 63,
 'from': '2026-06-05T00:00:00Z',
 'to': '2026-08-13T00:00:00Z',
 'series': {'devlogs': [{'ts': '2026-06-05T00:00:00Z', 'v': 1, 'synthetic': True},
                        {'ts': '2026-06-06T00:00:00Z',
                         'v': 2,
                         'd': 1,
                         'synthetic': True},
                        {'ts': '2026-06-07T00:00:00Z',
                         'v': 3,
                         'd': 1,
                         'synthetic': True}],
            'likes': [{'ts': '2026-08-04T00:00:00Z', 'v': 273},
                      {'ts': '2026-08-05T00:00:00Z', 'v': 273, 'd': 0},
                      {'ts': '2026-08-13T00:00:00Z', 'v': 286, 'd': 13}]},
 'entity': {'type': 'project',
            'id': 8100,
            'title': 'Nixie Tube Desk Clock',
            'owner': 'quartzfox'},
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

DEVLOG_LIST = {'q': None,
 'sort': 'posted_at',
 'order': 'desc',
 'days': None,
 'total': 2969,
 'limit': 1,
 'offset': 0,
 'items': [{'_id': 39084,
            'body_preview': 'Boost converter finally holds 170 V without screaming. '
                            'Photos below.',
            'comments': 0,
            'comments_stale': False,
            'duration_seconds': 13191,
            'last_crawled': '2026-08-18T09:12:44Z',
            'likes': 0,
            'media': [{'kind': 'video',
                       'url': 'https://example.com/project',
                       'poster': 'https://stardance.example/uploads/banner.png'}],
            'post_id': 46488,
            'posted_at': '2026-08-13T18:43:57Z',
            'project_id': 927,
            'reposts': 0,
            'snapshot_at': '2026-08-18T09:12:44Z',
            'username': 'tubefox',
            'username_lower': 'tubefox',
            'views': 2,
            'project_title': 'Split Keyboard',
            'project_banner_url': 'https://stardance.example/uploads/banner.png',
            'is_super_star': False,
            'is_hardware': False,
            'avatar_url': None,
            'rank': None}],
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

DEVLOG = {'_id': 39084,
 'body_preview': 'Boost converter finally holds 170 V without screaming. Photos below.',
 'comments': 0,
 'comments_stale': False,
 'duration_seconds': 13191,
 'last_crawled': '2026-08-18T09:12:44Z',
 'likes': 0,
 'media': [{'kind': 'video',
            'url': 'https://example.com/project',
            'poster': 'https://stardance.example/uploads/banner.png'}],
 'post_id': 46488,
 'posted_at': '2026-08-13T18:43:57Z',
 'project_id': 927,
 'reposts': 0,
 'snapshot_at': '2026-08-18T09:12:44Z',
 'username': 'tubefox',
 'username_lower': 'tubefox',
 'views': 2,
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

DEVLOG_COMMENTS = {'devlog_id': 7145,
 'project_id': 8100,
 'comments_count': 4,
 'total': 4,
 'items': [{'_id': 1227,
            'body': 'Boost converter finally holds 170 V without screaming. Photos '
                    'below.',
            'body_length': 68,
            'devlog_id': 7145,
            'first_seen': '2026-08-13T22:49:03.280000Z',
            'images': [],
            'is_self': False,
            'last_crawled': '2026-08-18T09:12:44Z',
            'mentions': [],
            'position': 0,
            'posted_at': '2026-06-14T17:06:35Z',
            'project_id': 8100,
            'username': 'quartzfox',
            'username_lower': 'quartzfox'}],
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

USER_SEARCH = {'query': 'The',
 'metric': 'ship_stardust',
 'total': 1,
 'items': [{'user_id': 11155,
            'username': 'quartzfox',
            'avatar_url': 'https://stardance.example/avatars/1177.png',
            'value': 3140,
            'rank': 1,
            'stats': {'followers': 22,
                      'following': 0,
                      'devlogs': 122,
                      'projects': 5,
                      'ships': 5,
                      'votes': 75,
                      'streak': 61,
                      'achievements_earned': 1,
                      'achievements_total': 11},
            'totals': {'ship_stardust': 3140,
                       'voted_stardust': 3140,
                       'mission_stardust': 0,
                       'hours': 277.88,
                       'shipped_hours': 176.0,
                       'paid_hours': 176.0,
                       'likes_received': 312,
                       'comments_received': 40,
                       'reposts_received': 9,
                       'views_received': 9103,
                       'best_multiplier': 19.78,
                       'avg_multiplier': 14.64,
                       'comments_sent': 0,
                       'comments_to_others': 0,
                       'comment_threads': 0,
                       'projects_commented': 0,
                       'comment_chars': 0,
                       'first_comment_at': None,
                       'last_comment_at': None,
                       'stardust_per_paid_hour': 17.84,
                       'avg_comment_length': None,
                       'comments_sent_per_received': 0.0,
                       'unpaid_hours': 101.88,
                       'ratable_unpaid_hours': 101.88,
                       'mission_pending_hours': 0.0,
                       'mission_pending_stardust': 0,
                       'estimated_pending_stardust': 1818,
                       'estimated_total_stardust': 4958},
            'exact': False}],
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

USER = {'_id': 11155,
 'avatar_kind': 'slack',
 'avatar_url': 'https://stardance.example/avatars/1177.png',
 'banner_url': 'https://stardance.example/uploads/banner.png',
 'bio': "Hi! I'm Jonah, a 18 year-old student from the UK and CEO of CRAW SYSTEMS. I "
        'specialise in Python, tool design, and low-level systems. My main project '
        'isCrawssembly, an assembly-like programming language that helps teach '
        'beginners how computers actually work. Give it a follow if you want to '
        'support open-source learning!',
 'first_seen': '2026-08-04T18:03:05.280000Z',
 'hidden': False,
 'joined_at': '2026-06-05T00:00:00Z',
 'last_changed': '2026-08-04T18:12:52.181000Z',
 'last_crawled': '2026-08-18T09:12:44Z',
 'project_ids': [8100, 18181, 19167, 19371, 41154],
 'project_ids_seen_at': '2026-08-04T18:12:52.181000Z',
 'slack_id': 'U0B8JV1RZB8',
 'stats': {'followers': 22,
           'following': 0,
           'devlogs': 122,
           'projects': 5,
           'ships': 5,
           'votes': 75,
           'streak': 61,
           'achievements_earned': 1,
           'achievements_total': 11},
 'username': 'quartzfox',
 'username_lower': 'quartzfox',
 'coverage': {'projects_listed': 5,
              'projects_seen': 5,
              'projects_reported': 5,
              'devlogs_seen': 125,
              'devlogs_reported': 122,
              'ships_seen': 5,
              'ships_reported': 5,
              'projects_missing': [],
              'complete': True},
 'totals': {'ship_stardust': 3140,
            'voted_stardust': 3140,
            'mission_stardust': 0,
            'hours': 277.88,
            'shipped_hours': 176.0,
            'paid_hours': 176.0,
            'likes_received': 312,
            'comments_received': 40,
            'reposts_received': 9,
            'views_received': 9103,
            'best_multiplier': 19.78,
            'avg_multiplier': 14.64,
            'comments_sent': 0,
            'comments_to_others': 0,
            'comment_threads': 0,
            'projects_commented': 0,
            'comment_chars': 0,
            'first_comment_at': None,
            'last_comment_at': None,
            'stardust_per_paid_hour': 17.84,
            'avg_comment_length': None,
            'comments_sent_per_received': 0.0,
            'unpaid_hours': 101.88,
            'ratable_unpaid_hours': 101.88,
            'mission_pending_hours': 0.0,
            'mission_pending_stardust': 0,
            'estimated_pending_stardust': 1818,
            'estimated_total_stardust': 4958},
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

USER_PROJECTS = {'user_id': 11155,
 'username': 'quartzfox',
 'total': 5,
 'items': [{'_id': 8100,
            'banner_url': 'https://stardance.example/uploads/banner.png',
            'created_at_estimate': '2026-06-05T18:56:50Z',
            'demo_url': 'https://example.com/project',
            'description': 'Six IN-14 tubes, a custom boost converter and far too much '
                           'brass.',
            'first_seen': '2026-08-04T18:03:06.470000Z',
            'is_hardware': False,
            'is_super_star': True,
            'last_changed': '2026-08-13T21:24:41.810000Z',
            'last_crawled': '2026-08-18T09:12:44Z',
            'members': ['quartzfox'],
            'owner_avatar_url': 'https://stardance.example/avatars/1177.png',
            'owner_username': 'quartzfox',
            'repo_url': 'https://example.com/project',
            'stats': {'devlogs': 111,
                      'total_hours': 266.0,
                      'summed_hours': 266.23,
                      'shipped_hours': 167.0,
                      'paid_hours': 167.0,
                      'followers': 74,
                      'likes': 286,
                      'comments': 39,
                      'reposts': 9,
                      'views': 8597,
                      'ships': 2,
                      'stardust_total': 3042,
                      'voted_stardust': 3042,
                      'mission_stardust': 0,
                      'latest_multiplier': 19.65,
                      'avg_multiplier': 19.715,
                      'stardust_per_paid_hour': 18.22,
                      'unpaid_hours': 99.23,
                      'ratable_unpaid_hours': 99.23,
                      'mission_pending_hours': 0.0,
                      'mission_pending_stardust': 0,
                      'estimated_pending_stardust': 1808,
                      'estimated_total_stardust': 4850,
                      'fixed_payout_hours': 0.0,
                      'flat_rate_hours': 0.0},
            'super_star_at': '2026-06-16T12:22:56Z',
            'super_star_by': 'cskartikey',
            'super_star_note': 'As a prize for your great work, look out for a bonus '
                               'prize in the mail :)',
            'title': 'Nixie Tube Desk Clock',
            'member_ids': [11155],
            'owner_id': 11155,
            'mission': None}],
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

USER_DEVLOGS = {'user_id': 11155,
 'username': 'quartzfox',
 'total': 125,
 'limit': 1,
 'offset': 0,
 'items': [{'_id': 38397,
            'avatar_url': 'https://stardance.example/avatars/1177.png',
            'body_preview': 'Boost converter finally holds 170 V without screaming. '
                            'Photos below.',
            'comments': 1,
            'comments_stale': False,
            'duration_seconds': 4109,
            'image_urls': ['https://stardance.example/uploads/banner.png'],
            'last_crawled': '2026-08-18T09:12:44Z',
            'likes': 5,
            'post_id': 45634,
            'posted_at': '2026-08-12T08:01:02Z',
            'project_id': 8100,
            'reposts': 0,
            'snapshot_at': '2026-08-18T09:12:44Z',
            'username': 'quartzfox',
            'username_lower': 'quartzfox',
            'views': 76,
            'user_id': 11155,
            'media': [{'kind': 'image', 'url': 'https://example.com/project'}],
            'body': 'Boost converter finally holds 170 V without screaming. Photos '
                    'below.',
            'comments_crawled_at': '2026-08-13T22:49:21.063000Z',
            'comments_crawled_count': 1,
            'comments_seen': 1}],
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

USER_COMMENTS = {'user_id': 11155,
 'username': 'quartzfox',
 'total': 12,
 'limit': 1,
 'offset': 0,
 'comments_received': 40,
 'items': [{'_id': 7173,
            'body': 'Boost converter finally holds 170 V without screaming. Photos '
                    'below.',
            'body_length': 68,
            'devlog_id': 33303,
            'first_seen': '2026-08-13T22:49:19.435000Z',
            'images': [],
            'is_self': True,
            'last_crawled': '2026-08-18T09:12:44Z',
            'mentions': [],
            'position': 1,
            'posted_at': '2026-08-03T10:19:32Z',
            'project_id': 8100,
            'username': 'quartzfox',
            'username_lower': 'quartzfox',
            'user_id': 11155}],
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

USER_SHIPS = {'user_id': 11155,
 'username': 'quartzfox',
 'total': 5,
 'stardust_total': 3140,
 'items': [{'_id': 20937,
            'post_id': 20937,
            'project_id': 8100,
            'ship_number': 2,
            'username': 'quartzfox',
            'shipped_at': '2026-07-02T17:49:35Z',
            'devlogs_at_ship': 13,
            'hours_at_ship': 33.0,
            'multiplier': 19.65,
            'payout': 633,
            'status': 'approved',
            'payout_blessing': None,
            'mission': None,
            'mission_slug': None,
            'body': 'Boost converter finally holds 170 V without screaming. Photos '
                    'below.',
            'payout_hours': 32.21,
            'payout_path': 'voting',
            'mission_stardust': None,
            'mission_pending_stardust': None,
            'username_lower': 'quartzfox',
            'last_crawled': '2026-08-18T09:12:44Z',
            'user_id': 11155}],
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

LEADERBOARD = {'metric': 'ship_stardust',
 'source': 'computed from crawled rows',
 'total': 1,
 'limit': 1,
 'offset': 0,
 'items': [{'rank': 1,
            'user_id': 11155,
            'username': 'quartzfox',
            'avatar_url': 'https://stardance.example/avatars/1177.png',
            'value': 3140,
            'complete': True}],
 'data_as_of': '2026-08-18T09:12:44Z',
 'stale': False}

LEADERBOARD_METRICS = {'metrics': ['best_multiplier',
             'comment_threads',
             'comments_received',
             'comments_sent',
             'comments_to_others',
             'devlogs',
             'estimated_total_stardust',
             'followers',
             'following',
             'hours',
             'likes_received',
             'paid_hours',
             'projects',
             'projects_commented',
             'ship_stardust',
             'shipped_hours',
             'ships',
             'stardust_per_paid_hour',
             'views_received',
             'votes'],
 'computed_by_us': ['best_multiplier',
                    'comment_threads',
                    'comments_received',
                    'comments_sent',
                    'comments_to_others',
                    'estimated_total_stardust',
                    'hours',
                    'likes_received',
                    'paid_hours',
                    'projects_commented',
                    'ship_stardust',
                    'shipped_hours',
                    'stardust_per_paid_hour',
                    'views_received'],
 'reported_by_profile': ['devlogs',
                         'followers',
                         'following',
                         'projects',
                         'ships',
                         'votes'],
 'note': 'ship_stardust counts ship payouts only. Upstream totals also include '
         'achievements, missions, reviewer and show-and-tell payouts and manual '
         'grants, none of which are public.'}

SHOP_LIST = {
    "region": "US",
    "total": 148,
    "limit": 100,
    "offset": 0,
    "items": [
        {
            "_id": 61,
            "name": "Soldering Station",
            "description": "Temperature-controlled, with a spare tip.",
            "url": "https://stardance.example/shop/items/61",
            "image_url": "https://stardance.example/uploads/shop/61.png",
            "categories": ["tools"],
            "enabled_regions": ["US", "EU", "UK", "IN", "CA", "AU", "XX"],
            "regions": ["US", "EU", "IN"],
            "regions_available": 3,
            "prices": {"US": 3200, "EU": 3350, "IN": 2900},
            "full_prices": {"US": 3200, "EU": 3350, "IN": 2900},
            "price_min": 2900,
            "price_max": 3350,
            "price_spread": 450,
            "on_sale": False,
            "sale_percentage": None,
            "purchases": 214,
            "is_new": False,
            "remaining_stock": 37,
            "out_of_stock": False,
            "achievement_locked": False,
            "mission_locked": False,
            "enabled_until": None,
            "hours_low": 18.0,
            "hours_high": 24.0,
            "region": "US",
            "price": 3200,
            "full_price": 3200,
            "last_crawled": "2026-08-18T09:12:44Z",
        }
    ],
    "data_as_of": "2026-08-18T09:12:44Z",
    "stale": False,
}

SHOP_ITEM = dict(SHOP_LIST["items"][0], data_as_of="2026-08-18T09:12:44Z", stale=False)

SHOP_REGIONS = {
    "regions": [
        {
            "region": "US",
            "name": "United States",
            "items": 148,
            "on_sale": 12,
            "cheapest": 25,
            "dearest": 41000,
            "median_price": 1850,
        },
        {
            "region": "XX",
            "name": "Rest of World",
            "items": 141,
            "on_sale": 11,
            "cheapest": 25,
            "dearest": 41000,
            "median_price": 1900,
        },
    ],
    "data_as_of": "2026-08-18T09:12:44Z",
    "stale": False,
}

GLOBAL = {
    "scope": "platform",
    "totals": {
        "users": 26104,
        "projects": 9418,
        "devlogs": 71330,
        "ships": 12045,
        "comments_seen": 48210,
        "users_known": 26851,
        "projects_known": 30388,
        "threads_pending": 35,
        "shop_items": 148,
        "shop_items_on_sale": 12,
        "hours": 412885.5,
        "shipped_hours": 388120.0,
        "paid_hours": 351044.25,
        "stardust_paid": 8842190,
        "likes": 194322,
        "comments": 51877,
        "reposts": 8801,
        "views": 2841009,
        "followers": 61204,
    },
    "data_as_of": "2026-08-18T09:12:44Z",
    "stale": False,
}

ASK = {
    "question": "which hardware projects earned the most stardust?",
    "title": "Top hardware projects by Stardust",
    "summary": "Ranked by stardust_total across projects marked as hardware.",
    "display": "table",
    "chart": None,
    "collection": "projects",
    "pipeline": [
        {"$match": {"is_hardware": True}},
        {"$sort": {"stats.stardust_total": -1}},
        {"$limit": 10},
        {"$project": {"title": 1, "stats.stardust_total": 1}},
    ],
    "columns": ["title", "stats.stardust_total"],
    "rows": [{"title": "Nixie Tube Desk Clock", "stats.stardust_total": 5120}],
    "row_count": 10,
    "truncated": False,
    "attempts": 1,
    "elapsed_ms": 2841,
    "model": "~deepseek/deepseek-v4-flash-latest",
}
